### ISSUE TITLE
Kohana v2

### ISSUE THREAD

**Issue by garbinmarcelo** [kilofox/kohana#3]
Hello how are you?

I found this repository through kohana.top. The Forum is not working, so I would have some questions.

I have a legacy system, I believe that the Kohana version is v2.3.4 as shown in the print below, is that it?
![image](https://user-images.githubusercontent.com/9335588/168094287-48f8c5bb-0fda-4b2b-a6bb-e8e5b6ab8574.png)

Could you tell me if I can get the documentation for it (v2)?

I need to create the "Remember me" function on login, would you have any material on this? Today the sessions are configured to use cookies, however many methods that I try to use according to the documentation on the kohana.top website end up with an error.

Example: `Fatal error:  Access to undeclared static property: Session::$default in`

Thank you in advance for your attention.

**Comment by muffetlab** [comment]
Sorry, I couldn't find the documentation of version 2, either.
